[project]
name = "obligationsinvestering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.14.15",
    "polars>=1.32.2",
]
